enum Language {
    AFAR = 'aa',
    ABKHAZIAN = 'ab',
    AFRIKAANS = 'af',
    AKAN = 'ak',
    AMHARIC = 'am',
    ARAGONENESE = 'an',
    ARABIC = 'ar',
    ASSAMESE = 'as',
    AVARIC = 'av',
    AYMARA = 'ay',
    AZERBAIJANI = 'az',
    BASHKIR = 'ba',
    BELARUSIAN = 'be',
    BULGARIAN = 'bg',
    BIHARI = 'bh',
    BISLAMA = 'bi',
    BAMBARA = 'bm',
    BENGALI = 'bn',
    TIBETAN = 'bo',
    BRETON = 'br',
    BOSNIAN = 'bs',
    CATALAN = 'ca',
    CHECHEN = 'ce',
    CHAMORRO = 'ch',
    CORSICAN = 'co',
    CREE = 'cr',
    CZECH = 'cs',
    CHURCH_SLAVIC = 'cu',
    CHUVASH = 'cv',
    WELSH = 'cy',
    DANISH = 'da',
    GERMAN = 'de',
    DIVEHI = 'dv',
    DZONGKHA = 'dz',
    EWE = 'ee',
    GREEK = 'el',
    ENGLISH = 'en',
    ESPERANTO = 'eo',
    SPANISH = 'es',
    ESTONIAN = 'et',
    BASQUE = 'eu'
}

 

export default Language;